BASE_YAML: "COCO-Detection/faster_rcnn_R_101_C4_3x.yaml"
DATASETS:
        TRAIN: ("daytime_clear_train",)
        TEST: ('night_rainy_train',)
        # daytime_clear_test'daytime_foggy_train','night_sunny_train','night_rainy_train','dusk_rainy_train')
DATALOADER:
        NUM_WORKERS: 8
INPUT:
        MIN_SIZE_TRAIN: (600,)
        MIN_SIZE_TEST: 600
        CLIP_RANDOM_CROPS: False
        RANDOM_CROP_SIZE: 400

SOLVER:
        BASE_LR: 0.002
        MAX_ITER: 50000
        STEPS: [40000,]       
        WARMUP_ITERS: 500
        IMS_PER_BATCH: 4
        CHECKPOINT_PERIOD: 10000
        REFERENCE_WORLD_SIZE: 2
        # WORLD_SIZE: 2
MODEL:
        BACKBONE:
                NAME: ClipRN101
        WEIGHTS: 'all_outs_freeze_all_gen_style/diverse_weather/model_0039999.pth'
        CLIP_IMAGE_ENCODER_NAME: 'RN101'
        META_ARCHITECTURE: 'ClipRCNNWithClipBackboneGenTrainable'

        PROPOSAL_GENERATOR:
                NAME: 'SBRPN'
        ROI_HEADS:
                NAME: 'ClipRes5ROIHead'        
                # BATCH_SIZE_PER_IMAGE: 128   # faster, and good enough for this toy dataset (default: 512)
                NUM_CLASSES: 7
TEST:
        EVAL_SAVE_PERIOD: 2000
OUTPUT_DIR: "all_outs/diverse_weather"
VIS_PERIOD: 5000


